# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BiteAIAPIExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BiteAIAPIExample
  pod "Apollo", "=0.8.0"
  pod "Alamofire", "~>4.5"
  pod "BiteAIClient", :path => '../../BiteAIClient.podspec'
  
  target 'BiteAIAPIExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BiteAIAPIExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
